/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Venn;

import org.junit.Test;


public class LibraryTest {
    /*@Test public void testSomeLibraryMethod() {
        LibraryTest classUnderTest = new LibraryTest();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.testSomeLibraryMethod());
    }*/
}
